spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  batch:
    jdbc:
      initialize-schema: embedded
springfox:
  documenration:
    swagger:
      use-model-v3: false
thymeleaf:
  cache: false
  check-template-location: true
  prefix: classpath:/templates/
  suffix: .html
  enabled: true
